Repository yandextaxitech/binaryprefs, pull requests merged in 2020-04, with the labels that each got.

#61 Add kotlin using item into ReadMe
  README.md
Labels: enhancement

#59 Copy cached byte arrays values to prevent outer modifications
  library/src/main/java/com/ironz/binaryprefs/serialization/strategy/impl/ByteArraySerializationStrategy.java
  library/src/test/java/com/ironz/binaryprefs/BinaryPreferencesTest.java
Labels: major bug

#63 Added interruption checks for future barriers
  library/src/main/java/com/ironz/binaryprefs/BinaryPreferencesBuilder.java
  library/src/main/java/com/ironz/binaryprefs/BinaryPreferencesEditor.java
  library/src/main/java/com/ironz/binaryprefs/event/BroadcastEventBridge.java
  library/src/main/java/com/ironz/binaryprefs/fetch/EagerFetchStrategy.java
  library/src/main/java/com/ironz/binaryprefs/fetch/LazyFetchStrategy.java
  library/src/main/java/com/ironz/binaryprefs/task/ScheduledBackgroundTaskExecutor.java
  library/src/main/java/com/ironz/binaryprefs/task/TaskExecutor.java
  library/src/main/java/com/ironz/binaryprefs/task/barrier/FutureBarrier.java
  library/src/main/java/com/ironz/binaryprefs/task/barrier/impl/InterruptableFutureBarrier.java
  library/src/main/java/com/ironz/binaryprefs/task/barrier/impl/UninterruptableFutureBarrier.java
  library/src/main/java/com/ironz/binaryprefs/task/barrierprovider/FutureBarrierProvider.java
  library/src/main/java/com/ironz/binaryprefs/task/barrierprovider/impl/InterruptableFutureBarrierProvider.java
  library/src/main/java/com/ironz/binaryprefs/task/barrierprovider/impl/UnInterruptableFutureBarrierProvider.java
  library/src/test/java/com/ironz/binaryprefs/PreferencesCreator.java
  library/src/test/java/com/ironz/binaryprefs/UnInterruptibleBinaryPreferencesTest.java
  library/src/test/java/com/ironz/binaryprefs/task/TestTaskExecutor.java
Labels: minor bug
